id: P008012
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:55:21.367863
source_metadata:
  id: bdr:W3CN7842
  title: སྡོམ་གསུམ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན་རྩ་འགྲེལ།
  author: ''
  volumes:
    442f0dc5a4854d8fa62d021fb236bd29:
      image_group_id: I3CN7844
      title: Volume 1 of sdom gsum 'jam dbyangs bla ma'i dgongs rgyan rtsa 'grel/
      volume_number: 1
      total_pages: 772
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
