id: P008012
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7842
  title: སྡོམ་གསུམ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན་རྩ་འགྲེལ།
  author: ''
  volumes:
    be17e2c2207e49caae6ffb48e2d72ad0:
      image_group_id: I3CN7844
      title: ''
      volume_number: 1
      total_pages: 772
ebook_metadata:
  title: སྡོམ་གསུམ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན་རྩ་འགྲེལ།
  author: ''
  sku: P008012
  cover: cover.jpg
  layers:
  - pagination
